##CONFIG SECTION##

config:
  tls: 
    rejectUnauthorized: false # DISABLE CERTIFICATE VALIDATION, FOR STAGE AND DEV TESTING ONLY
  target: 'http://devapi.gonnachallenge.com'
  http: 
      pool: 10 # All HTTP requests from all virtual users will be sent over the same 10 connections, To open and re-use a fixed number of connections
  ensure:
    maxErrorRate: 1
  plugins:
    expect: {}
    fuzzer: {}
    metrics-by-endpoint: {}
    # statsd:
    #   host: "localhost"
    #   port: 8125
    #   prefix: "artillery"
    #     publish-metrics:
    #       - type: datadog  #config to publish metrics to datadog via its HTTPS API
  phases:
    - duration: 60
      arrivalRate: 1
      name: "low load"

    - duration: 10
      arrivalRate: 5
      name: "medium load"

    - duration: 10
      arrivalRate: 3
      rampTo: 50
      name: "ramp up"

  #SETUP VARIABLES HERE
  variables:
    max_items:
      - "1000"
  defaults:
    headers:
      Authorization: 'bearer AQBd_Jq-OCXXQLaIGf8Fn7R256WWzrd_g4KWCOCAFE8tkyfIwCR3fh5GrJf93kf6PA0f9wZYrO7V6_EbI3e4_SAe1FfxQaNAZpOvoV2gGJMN3MRGtUWvlo47TT0YFK6zLmWiP6NB6zFPm0BmHYS96JuWEggCeyngQFk6FhB4fd5buZ_dxXkzAcQMkwRQ8DaosZuQ0-ARg_dAmCzCXauM2IWbuawHmRl3TUt32pBJP8cN81c_ncwvZvUFe38HjTsfj8fI9BoeUHAoih4t5W7VyCspLdb1rtYdpXkZo6U9OqCA4FG1NsChB8iPoZA2bf79PTX7IsnHjSIYkncqsE_dZUvQ'
