##CONFIG SECTION##

config:
  tls: 
    rejectUnauthorized: false # DISABLE CERTIFICATE VALIDATION, FOR STAGE AND DEV TESTING ONLY
  http: 
    timeout: 10
    pool: 10 # All HTTP requests from all virtual users will be sent over the same 10 connections, to open and re-use a fixed number of connection
  ensure:
    maxErrorRate: 5

  plugins: # Import plugins
    expect: {}
    fuzzer: {}

  target: 'http://staging.api.gonna.netzon.se' # baseURL of API

  phases:
    - duration: 10 #Duration of test will be running
      arrivalRate: 5 #Arrival of new virtual user per second (average virtual users)
      name: "Normal Load" #Name of phase. Can set multiple phases
    
    - pause: 10 #Pauses for 10 seconds, no virtual users created in this duration

  # SETUP VARIABLES HERE
  variables: 
    max_items: 
      - "1000"
  defaults:
    headers: #Setup required authorization here, if there is any, before starting to execute load test
      Authorization: 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmltYXJ5c2lkIjoiYjRmYTlhN2ItMmVlZi00ZDYwLWFhNDItZWM3ZTc0M2FjMjg4Iiwicm9sZSI6IkFwcFVzZXIiLCJuYmYiOjE1NzE3MjA4NzMsImV4cCI6MTU3Njk3Njg3MywiaWF0IjoxNTcxNzIwODczfQ.K18MLxZmQEA1fnakKszvuiOJUymbmm-gHSDzvKw2jSU'

## END OF CONFIG