##CONFIG SECTION##

config:
  tls: 
    rejectUnauthorized: false # DISABLE CERTIFICATE VALIDATION, FOR STAGE AND DEV TESTING ONLY
  http: 
    timeout: 10
    pool: 10 # All HTTP requests from all virtual users will be sent over the same 10 connections, to open and re-use a fixed number of connection
  ensure:
    maxErrorRate: 5

  plugins: # Import plugins
    expect: {}
    fuzzer: {}

  target: 'https://static.tempest.hope.addimedical.netzon.se/api' # baseURL of API

  phases:
    - duration: 1  #Duration of test will be running
      arrivalRate: 1 #Arrival of new virtual user per second (average virtual users)
      name: "Normal Load" #Name of phase. Can set multiple phases

    # - duration: 1  #Duration of test will be running
    #   arrivalRate: 1 #Arrival of new virtual user per second (average virtual users)
    #   name: "Endurance Testing" #Name of phase. Can set multiple phases

    ##- pause: 1 #Pauses for 1 second(s), no virtual users created in this duration


  # SETUP VARIABLES HERE
  variables:

    ## Add careplan variables
    patientGUID:
      - "69bfb380-da59-4ae6-b083-0fedbd59c285"
    healthIssue:
      - "I64-"
    careplanName:
      - "Any careplan name (Artillery)"

    ## Add recurring activities variables
    careplanGUID:
      - "d3c5b0cf-17b1-48fb-a820-58db89c23fd7"
    activityCode:
      - "HT.Weight"
    repeatCount: ## Recurring Activity - number of times recurring activity is created
      - "1" 
    period: ## Recurring Activity - Interval per day //// This repeatCount = 10 and period = 1 value will create 1 recurring activity each day for 10 days
      - "1"
    startDateTime:
      - "Sun, 14 Jun 2020 16:00:00 GMT" ## Please follow the format e.g. Sat, 15 Feb 2020 16:00:00 GMT
    endDateTime:
      - "Mon, 27 Jul 2020 15:59:59 GMT" ## Please follow the format e.g. Sat, 20 Jun 2020 16:00:00 GMT

    ## POST Eform Instance
    activityGUID: "5b53c13d-8fd7-4e93-8d2c-be445398f0c4" 

    ## GET Eform Instance
    eformInstanceGUID: "033b6cd2-6173-43a9-80ed-2348ae53da3d" 

    pairingCodeToken:
    - "ceZ03iAIlCqykgUkuMmP04sBqzgRfNE6Y6yqDghHhQb2HRXxZDkDJPwBxlb2BJbWCvutlMyUsA6oGYLDyR9zgA%3D%3D"
    max_items: 
      - "10000"

  defaults:
    headers: #Setup required authorization here, if there is any, before starting to execute load test
      ServiceAccountAuthorization: 'bearer PRE-PROD_5K'
      Authorization: 'bearer eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9hdXRoZW50aWNhdGlvbiI6IntcInN0YXR1c1wiOjAsXCJwcmluY2lhbFwiOm51bGwsXCJzZXNzaW9uXCI6e1wic2Vzc2lvbklkXCI6XCIyMTQ5MGEwYy1hMWY0LTQ3ZTktYTVlMC02NGQ2ZTk0MTgwYjZcIixcInVzZXJSZWZcIjp7XCJndWlkXCI6XCIzNTQzZGFmZC1lZjYyLTQ2ZTEtYmYyOC0xNjlhY2M3YTg0YmRcIixcInZlcnNpb25cIjpudWxsLFwidGl0bGVcIjpcIlRlY2ggU3Vwb3J0XCJ9LFwidXNlcklkXCI6e1widHlwZVwiOntcImNvZGVcIjpcIlwiLFwic3lzdGVtXCI6XCJcIn0sXCJzeXN0ZW1cIjpcIlwiLFwidmFsdWVcIjpcIlNVUFBPUlQwMVwifSxcInJvbGVcIjoxLFwibG9naW5NZXRob2RcIjp7XCJjb2RlXCI6XCJUb2tlblwiLFwic3lzdGVtXCI6XCJIT1BFLkxvZ2luTWV0aG9kXCJ9LFwiZXhwaXJlc1wiOlwiMjAyMy0wMy0xMlQwMzo1NToxMS4yNzQ3ODU4WlwiLFwiY29tbWlzc2lvblwiOntcImlkXCI6bnVsbCxcImF0dHJpYnV0ZXNcIjpbe1wibmFtZVwiOlwiXCIsXCJ2YWx1ZVwiOlwiXCJ9XX0sXCJvcmdSZWZcIjp7XCJndWlkXCI6XCJjZTM0Yzc0NS1mYTY4LTRmMDQtYjFiZi1kYmU1MWUxOTkzMDhcIixcInZlcnNpb25cIjpudWxsLFwidGl0bGVcIjpcIlPDtmRyYSDDhGx2c2JvcmdzIHNqdWtodXNcIn0sXCJvcmdJZFwiOntcInR5cGVcIjp7XCJjb2RlXCI6XCJcIixcInN5c3RlbVwiOlwiXCJ9LFwic3lzdGVtXCI6XCJcIixcInZhbHVlXCI6XCJWR1IwMDlcIn0sXCJoZWFsdGhDYXJlUHJvdmlkZXJJZFwiOntcInR5cGVcIjp7XCJjb2RlXCI6XCJcIixcInN5c3RlbVwiOlwiXCJ9LFwic3lzdGVtXCI6XCJcIixcInZhbHVlXCI6XCJWR1JcIn0sXCJoZWFsdGhDYXJlVW5pdElkXCI6bnVsbCxcImFjY291bnRcIjpcIlBSRS1QUk9EXzVLXCIsXCJ0aW1lem9uZVwiOlwiMDA6MDA6MDBcIixcImV4dGVuc2lvblwiOlt7XCJuYW1lXCI6XCJcIixcInZhbHVlXCI6XCJcIn0se1wibmFtZVwiOlwiSE9QRS5BbGlhc1wiLFwidmFsdWVcIjpcIlRTXCJ9LHtcIm5hbWVcIjpcIkhPUEUuQ2hhdFwiLFwidmFsdWVcIjpcIllcIn0se1wibmFtZVwiOlwiSE9QRS5Qcm9mZXNzaW9uYWxUaXRsZVwiLFwidmFsdWVcIjpcIlN1cHBvcnRcIn1dfSxcInNlc3Npb25LZXlcIjpcIm1vaE5JZCtDS1FnSU44Z1ZXMDN2dTBhV24vTnZsK0JqcVhGU2libzlPajEyaUpJc0twZ0FtTis4VW5VVUw4eTBTbmJwMHplcThUaEFUN3ZuRS9TbzBnPT1cIn0iLCJuYmYiOjE1OTIyNzk3MTEsImV4cCI6MTU5Mjg3OTY1MSwiaWF0IjoxNTkyMjc5NzExfQ.uHryAXmmKCXyixXLrS2w9WUB57YQBNPDLPKosux7VTs'
      Accept-Language: 'en'
      accept: application/json
      Content-Type: application/json-patch+json
    

## END OF CONFIG

