##CONFIG SECTION##

config:
  tls: 
    rejectUnauthorized: false # DISABLE CERTIFICATE VALIDATION, FOR STAGE AND DEV TESTING ONLY
  http: 
    pool: 10 # All HTTP requests from all virtual users will be sent over the same 10 connections, To open and re-use a fixed number of connections
  ensure:
    maxErrorRate: 5
  plugins: # Installed plugins
    expect: {}
    fuzzer: {}
    metrics-by-endpoint: {}

  target: 'http:/'
  phases:
    - duration: 120 #Duration of test will be running
      arrivalRate: 10 #Arrival of new virtual user per second (average virtual users)
      rampTo: 50
      name: "Ramp up and sustain load"

    - pause: 3 #Pauses for 3 seconds, no virtual users created in this duration

    - duration: 600
      arrivalRate: 50
      name: "Sustained max load"

  #SETUP VARIABLES HERE
  variables:
    max_items:
      - "1000"
  defaults:
    headers:
      Authorization: 'bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmltYXJ5c2lkIjoiZGI5MjJiOTEtMzQ5My00YjU4LWIwY2MtOTRmMTYwY2JjYTA0Iiwicm9sZSI6IkFwcFVzZXIiLCJuYmYiOjE1NzA3MDQxNTUsImV4cCI6MTU3NTk2MDE1NSwiaWF0IjoxNTcwNzA0MTU1fQ.G47nncFDOQZN-aQLVN_tcOyD-HHx1tmlLQ4Lyz-n6w8'

## END OF CONFIG